services:
  db_postgresql:
    platform: linux/amd64
    image: postgres:13.3
    ports:
      - "127.0.0.1:5432:5432"
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql/data